selection_foreground    #e1e4d9
selection_background    #a9d292

background              #11140f
foreground              #e1e4d9

color0                  #43483e
color1                  #ffb4ab
color2                  #a9d292
color3                  #a0cfd0
color4                  #bccbb0
color5                  #bccbb0
color6                  #a9d292
color7                  #c3c8bb
color8                  #c3c8bb
color9                  #ffb4ab
color10                 #a9d292
color11                 #a0cfd0
color12                 #bccbb0
color13                 #bccbb0
color14                 #bccbb0
color15                 #e1e4d9

cursor                  #c3c8bb
cursor_text_color       #11140f

url_color               #bccbb0

active_tab_foreground   #e1e4d9
active_tab_background   #a9d292
inactive_tab_foreground #c3c8bb
inactive_tab_background #1d211a
