selection_foreground    #eee0d4
selection_background    #f8bb71

background              #18120c
foreground              #eee0d4

color0                  #504539
color1                  #ffb4ab
color2                  #f8bb71
color3                  #bbcd9e
color4                  #dfc2a2
color5                  #dfc2a2
color6                  #f8bb71
color7                  #d4c4b5
color8                  #d4c4b5
color9                  #ffb4ab
color10                 #f8bb71
color11                 #bbcd9e
color12                 #dfc2a2
color13                 #dfc2a2
color14                 #dfc2a2
color15                 #eee0d4

cursor                  #d4c4b5
cursor_text_color       #18120c

url_color               #dfc2a2

active_tab_foreground   #eee0d4
active_tab_background   #f8bb71
inactive_tab_foreground #d4c4b5
inactive_tab_background #251e17
