selection_foreground    #e1e4d9
selection_background    #abd28f

background              #11140e
foreground              #e1e4d9

color0                  #43483e
color1                  #ffb4ab
color2                  #abd28f
color3                  #a0cfcf
color4                  #bdcbaf
color5                  #bdcbaf
color6                  #abd28f
color7                  #c4c8bb
color8                  #c4c8bb
color9                  #ffb4ab
color10                 #abd28f
color11                 #a0cfcf
color12                 #bdcbaf
color13                 #bdcbaf
color14                 #bdcbaf
color15                 #e1e4d9

cursor                  #c4c8bb
cursor_text_color       #11140e

url_color               #bdcbaf

active_tab_foreground   #e1e4d9
active_tab_background   #abd28f
inactive_tab_foreground #c4c8bb
inactive_tab_background #1d211a
