selection_foreground    #e2e2e9
selection_background    #adc6ff

background              #111318
foreground              #e2e2e9

color0                  #44474f
color1                  #ffb4ab
color2                  #adc6ff
color3                  #debcdf
color4                  #bfc6dc
color5                  #bfc6dc
color6                  #adc6ff
color7                  #c4c6d0
color8                  #c4c6d0
color9                  #ffb4ab
color10                 #adc6ff
color11                 #debcdf
color12                 #bfc6dc
color13                 #bfc6dc
color14                 #bfc6dc
color15                 #e2e2e9

cursor                  #c4c6d0
cursor_text_color       #111318

url_color               #bfc6dc

active_tab_foreground   #e2e2e9
active_tab_background   #adc6ff
inactive_tab_foreground #c4c6d0
inactive_tab_background #1e1f25
