selection_foreground    #ece1d4
selection_background    #efbf6d

background              #17130b
foreground              #ece1d4

color0                  #4e4639
color1                  #ffb4ab
color2                  #efbf6d
color3                  #b4cea5
color4                  #dac3a1
color5                  #dac3a1
color6                  #efbf6d
color7                  #d2c5b4
color8                  #d2c5b4
color9                  #ffb4ab
color10                 #efbf6d
color11                 #b4cea5
color12                 #dac3a1
color13                 #dac3a1
color14                 #dac3a1
color15                 #ece1d4

cursor                  #d2c5b4
cursor_text_color       #17130b

url_color               #dac3a1

active_tab_foreground   #ece1d4
active_tab_background   #efbf6d
inactive_tab_foreground #d2c5b4
inactive_tab_background #241f17
