selection_foreground    #efe0d6
selection_background    #ffb77b

background              #19120c
foreground              #efe0d6

color0                  #51443b
color1                  #ffb4ab
color2                  #ffb77b
color3                  #c4cb97
color4                  #e3c0a5
color5                  #e3c0a5
color6                  #ffb77b
color7                  #d6c3b6
color8                  #d6c3b6
color9                  #ffb4ab
color10                 #ffb77b
color11                 #c4cb97
color12                 #e3c0a5
color13                 #e3c0a5
color14                 #e3c0a5
color15                 #efe0d6

cursor                  #d6c3b6
cursor_text_color       #19120c

url_color               #e3c0a5

active_tab_foreground   #efe0d6
active_tab_background   #ffb77b
inactive_tab_foreground #d6c3b6
inactive_tab_background #261e18
