general {
    lock_cmd = pidof hyprlock || hyprlock          # dbus/sysd lock command
    unlock_cmd = pkill -USR1 hyprlock              # dbus/sysd unlock command
    before_sleep_cmd = loginctl lock-session       # lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on     # turn on display after resuming
}

# 1. Dim screen 
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# 2. Lock screen 
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off display
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend system 
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}

# 5. Screentime Idle Detection
listener {
    timeout = 60
    on-timeout = ~/.local/bin/screentime_daemon --idle
    on-resume = ~/.local/bin/screentime_daemon --resume
}
