[pyprland]
plugins = ["scratchpads", "layout_center", "expose"]

[scratchpads.term]
command = "kitty --class=kitty.pypr"
class = "kitty.pypr"
size = "30% 90%"
position = "1% 5%"
animation = "fromLeft"
lazy = true

[layout_center]
margin = 60
